# Generated by Django 5.2.1 on 2025-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_transition', models.FloatField()),
                ('hour_transition', models.TimeField()),
                ('suspect', models.BooleanField(default=False)),
            ],
        ),
    ]
