# Generated by Django 5.2.1 on 2025-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_value', models.FloatField()),
                ('send_prev_balance', models.FloatField()),
                ('send_new_balance', models.FloatField()),
                ('recipient_prev_balance', models.FloatField()),
                ('recipient_new_balance', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
