# Generated by Django 5.2.1 on 2025-05-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_recipient_new_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='send_new_balance',
            new_name='sender_new_balance',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='send_prev_balance',
            new_name='sender_prev_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='suspect',
            field=models.BooleanField(default=False),
        ),
    ]
