# Generated by Django 5.2.1 on 2025-05-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_send_new_balance_transaction_sender_new_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient_new_balance',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='suspect',
            new_name='is_fraud',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient_prev_balance',
            new_name='new_balance_dest',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_new_balance',
            new_name='new_balance_orig',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_prev_balance',
            new_name='old_balance_dest',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_value',
            new_name='old_balance_org',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
